name: release-onsem

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'README.md'
    - 'test/**'
    - '.vscode/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
    	uses: actions/checkout@v2
    
    - name: Tag
    	uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Build
      run: npm run build
    
    - name: Zip
      run: zip -r build .
    
    - name: Release
    - uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        artifacts: "build.zip"
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
