name: release-onsem

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'README.md'
    - 'test/**'
    - '.vscode/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      name: Checkout

    - name: Install
      run: npm install

    - name: Build
      run: npm run build
    
    - name: Zip
      run: zip -r build .
    
    - uses: svenstaro/upload-release-action@v2
      name: Release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: 0.1.0
        asset_name: build.zip
        file: ./build.zip
