name: release-onsem

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'README.md'
    - 'test/**'
    - '.vscode/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      name: Checkout

    - name: Get Tags
      run: |
        git fetch --prune --unshallow --tags
        echo exit code $?
        git tag --list

    - name: Install
      run: npm install

    - name: Build
      run: npm run build
    
    - name: Zip
      run: cd build && zip -r ../build.zip .
    
    - name: Get next version
      id: get-next-version
      run: |
        echo "::set-output name=version::$(node get-next-version.js)"
    
    - uses: svenstaro/upload-release-action@v2
      name: Release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.get-next-version.outputs.version }}
        asset_name: build.zip
        file: ./build.zip
        overwrite: true
